[Site] update student list
cs3216/cs3216.github.io pull request #14
Opened 2017-08-16 11:43 UTC by Tzyinc

2017-08-16 12:57 UTC, yangshun requested changes

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/contactlist.csv
> +Name,Email,Faculty,Year,Role,Contact,Blog,Blog Feed,One-liner,Interests
😱 We shouldn't commit all their contact details into the repo

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/createNewYml.js
> +var csvFilename = 'contactlist.csv'
We should remove the CSV file and just add the headers here as reference for future batches to use.

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/createNewYml.js
> +  // console.log(json)
Remove console.logs

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/createNewYml.js
> +  json.map(function (value) {
You're using map here but not returning anything (you're mutating the value instead). Perhaps you should be using `.forEach`?

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/createNewYml.js
> +    value.id = value[nameKey].toLowerCase().replaceAll(' ', '-')
This operation is called slugify. Doing lower case and replacing spaces with hyphen won't cover all possible cases that might be present in future batches. Would recommend to use a node package to do the slugification instead.

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/createNewYml.js
> +    // console.log(oldStr)
Remove console.log

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/createNewYml.js
> +      newStr += '\n  - name: ' + student[nameKey]
Can use ES6 template strings instead

2017-08-16 12:57 UTC, yangshun commented on _data/students.yml
> +    blog: 	 http://cs3216shijie.blogspot.com/
Weird spacing here. Maybe the strings should be trimmed

2017-08-16 12:57 UTC, yangshun commented on TA_Scripts/Update_Students/createNewYml.js
> +      newStr += '\n  - name: ' + student[nameKey]
Trim all the values just in case

2017-08-16 13:12 UTC, Tzyinc commented on TA_Scripts/Update_Students/contactlist.csv
> +Name,Email,Faculty,Year,Role,Contact,Blog,Blog Feed,One-liner,Interests
oh ya good point

2017-08-16 13:13 UTC, yangshun commented on TA_Scripts/Update_Students/dependancies/csv.js
> +var fs = require('fs');
Just use the npm version

2017-08-18 06:30 UTC, ianngiaw commented on _data/students.yml
> +    faculty: "FASS, Engineering, Business, Computing, SDE, Science"
I think Aaron is Yale-NUS so he put all faculties. Shall we change this?

2017-09-03 13:53 UTC, louietyj commented
I did some minor clean ups, let's merge this first so that it shows up on the website and then if we want we can come back and update the script.

2017-09-03 13:53 UTC, merged